import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { requireRole } from '@/lib/api-auth'
import { generateSecurityReport } from '@/app/api/verify-security'

/**
 * Admin endpoint to verify that all security checks are in place
 * Restricted to admin users only
 */
export async function GET() {
  try {
    const supabase = await createClient()
    const auth = await requireRole(supabase, ['admin'])

    if (!auth.ok) {
      return auth.response
    }

    console.log('[SECURITY_REPORT] Generated by admin:', auth.userId)

    const report = await generateSecurityReport()

    return NextResponse.json(report, { status: 200 })
  } catch (error) {
    console.error('[SECURITY_REPORT_ERROR]', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Security check failed' },
      { status: 500 }
    )
  }
}
